name: Doc
on:
  push:
    branches:
      - master
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Generate doc
      run: |
        yarn install
        yarn doc

    - name: Deploy doc
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: apidoc
